--- #YAML:1.0
name:                XSLoader
version:             0.07
abstract:            Dynamically load C libraries into Perl code
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.30_04
author:              ~
distribution_type:   module
requires:     
    Test::More:                    0.62
meta-spec:
    url: http://module-build.sourceforge.net/META-spec-new.html
    version: 1.1
